### ISSUE TITLE
Libomptarget fatal error 1

### ISSUE THREAD

**Issue by kenyibo** [exasmr/openmc#27]
hi everyone,
when I launch with "openmc --event", I encountered an error

`"PluginInterface" error: Failure to synchronize stream (nil): Error in cuStreamSynchronize: misaligned address
Libomptarget error: Consult https://openmp.llvm.org/design/Runtimes.html for debugging options.
event.cpp:314:3: Libomptarget fatal error 1: failure of target construct while offloading is mandatory
`
May i ask how can I solve this problem?

![image](https://user-images.githubusercontent.com/130833685/232740683-4fecae52-ca41-474c-a112-3ef6059c6fbe.png)
[log.txt](https://github.com/exasmr/openmc/files/11260396/log.txt)

**Comment by jtramm** [comment]
Thanks for reporting this!

Can you give us more info on your system and environment? E.g., which card, which OS, which version of LLVM, and which version of CUDA are you using? What does you cmake line look like for compiling OpenMC? What version of OpenMC are you using? Are you able to successfully run simple CUDA applications? Are you able to successfully run simple OpenMP offloading applications?

Good test cases to confirm your environment is working are:

XSBench (both CUDA and OpenMP offloading versions): https://github.com/ANL-CESAR/XSBench

and the OpenMP "Hello world": 

```C++
#include <stdio.h>
#include <omp.h>
#include <math.h>
int main( int argv, char** argc ) {
  int is_initial = omp_is_initial_device();
#pragma omp target map(from:is_initial)
  {
    is_initial = omp_is_initial_device();
  }
  if( !is_initial )
    printf( "Hello world from accelerator.\n" );
  else
    printf( "Hello world from host.\n" );
  return 0;
}
```

**Comment by kenyibo** [comment]
Hi, this is my system information and environment:

- OS: Ubuntu 20.04.4 LTS
- card: Tesla V100-PCIE-32GB
- LLVM version: 16.0.1
- CUDA version:11.6
I downloaded the most recent version of the openmc so the version of openmc is 0.13.0

This is the OpenMC compile log,
[openmc_cmake_log.txt](https://github.com/exasmr/openmc/files/11268576/openmc_cmake_log.txt)
[openmc_make_log.txt](https://github.com/exasmr/openmc/files/11268577/openmc_make_log.txt)

and , I successfully compiled and executed the programs in the cuda folder and openmp-offload folder in XSBench. this is the out put log .
[openmp-offloda_log.txt](https://github.com/exasmr/openmc/files/11268607/openmp-offloda_log.txt)
[cuda_log.txt](https://github.com/exasmr/openmc/files/11268608/cuda_log.txt)

thanks

**Comment by jtramm** [comment]
Thanks for the information! Based on this, it looks like something may be wrong with your LLVM install. The OpenMP XSBench run is 40x slower than the CUDA version, which indicates it may be running on the host. It is expected that it would run at approximately the same rate as the CUDA version. You can test this by setting the following environment variable to enforce offloading to device:

```C++
OMP_TARGET_OFFLOAD=MANDATORY
```

You might also try running OpenMC with that variable set as well to see if this is indeed the problem.

**Comment by kenyibo** [comment]
The program ran normally after I replaced the new cross section data files

**Comment by kenyibo** [comment]
The program ran normally after I replaced the new cross section data files
